### PR TITLE
Fix issue with new_header.html not found during make doc

### PR DESCRIPTION
**Pull request by sowo**
Hi,

I needed to adjust the paths to the header, footer and styleshheet files to be able to build the documentation.

Thank you,
Wolfgang

### CODE REVIEW

**Comment by tblattner** [comment]
Thanks for the fix! Merging now.

**Comment by tblattner** [comment]
Also as of last week, we got approval to host the doxygen documentation on-line. I just finished getting it setup today.

https://pages.nist.gov/hedgehog

**Comment by sowo** [comment]
Hi Tim,

I hope you are doing well.

...that makes life easier. :) I'm very delayed in starting the port to
hedgehog as you might have guessed meanwhile. I hope things will slow down
now and that I find some time during the upcoming vacation season to work
on it.

Best,
Wolfgang

**Comment by tblattner** [comment]
Wolfgang,

Not a problem! The pandemic has certainly been an interesting challenge, which was one reason for the delay in getting the documentation onto the public facing site. I am sure you and your group are facing similar challenges. 

As always, feel free to ping us if you have any questions/concerns as you port things. 

Kind Regards,
Tim

**Pull request merged**
